name: TeX Live on macOS
env:
  cache-version: v12
on: [push, pull_request]

permissions:
  contents: read

jobs:
  macosx:
    runs-on: macos-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v4
    - name: Set up PATH
      run: |
        echo "/Users/runner/texlive/bin/x86_64-darwin" >> $GITHUB_PATH
        echo "/Users/runner/texlive/bin/universal-darwin" >> $GITHUB_PATH
    - name: Cache TeX Live
      id: cache-texlive
      uses: actions/cache@v4
      with:
        path: /Users/runner/texlive
        key: ${{ env.cache-version }}-${{ runner.os }}-texlive-essential
        restore-keys: |
          ${{ env.cache-version }}-${{ runner.os }}-texlive-essential
    - name: Download install-tl.zip
      run: |
        curl -s -O -L http://mirror.ctan.org/systems/texlive/tlnet/install-tl.zip
        unzip -q install-tl.zip
        mv install-tl-2* install-tl-dir
      if: steps.cache-texlive.outputs.cache-hit != 'true'
    - name: Run install-tl
      run: |
        install-tl-dir/install-tl --profile test/config/texlive_mac.profile
      if: steps.cache-texlive.outputs.cache-hit != 'true'
    - name: Run tlmgr install
      run: |
        tlmgr install collection-latex
        tlmgr install import subfiles latexmk makeindex
        tlmgr install chktex lacheck latexindent
      if: steps.cache-texlive.outputs.cache-hit != 'true'
    - name: Download latexindent binary
      run: |
        curl -s -O -L http://mirrors.ctan.org/support/latexindent/bin/macos/latexindent
        [ -d /Users/runner/texlive/bin/x86_64-darwin/ ] && mv -f latexindent /Users/runner/texlive/bin/x86_64-darwin/latexindent && chmod +x /Users/runner/texlive/bin/x86_64-darwin/latexindent || [ -d /Users/runner/texlive/bin/universal-darwin/ ] && mv -f latexindent /Users/runner/texlive/bin/universal-darwin/latexindent && chmod +x /Users/runner/texlive/bin/universal-darwin/latexindent
      if: steps.cache-texlive.outputs.cache-hit != 'true'
    - uses: actions/setup-node@v4
      with:
        node-version: '18'
    - run: |
        perl -v
        perl -MCwd -e 'print $Cwd::VERSION."\n";'
    - run: |
        latex -v
        latexmk -v
    - run: |
        npm ci
        npm run compile
    - name: Run tests
      run: npm run test
    - name: Archive test logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-log
        path: test/log/**/*.log
