name: TeX Live on Linux
env:
  cache-version: v12
on: [push, pull_request]

permissions:
  contents: read

jobs:
  linux:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v4
    - name: Set up PATH
      run: |
        echo "/tmp/texlive/bin/x86_64-linux" >> $GITHUB_PATH
    - name: Cache TeX Live
      id: cache-texlive
      uses: actions/cache@v4
      with:
        path: /tmp/texlive
        key: ${{ env.cache-version }}-${{ runner.os }}-texlive-essential
        restore-keys: |
          ${{ env.cache-version }}-${{ runner.os }}-texlive-essential
    - name: Download install-tl.zip
      run: |
        curl -s -O -L http://mirror.ctan.org/systems/texlive/tlnet/install-tl.zip
        unzip -q install-tl.zip
        mv install-tl-2* install-tl-dir
      if: steps.cache-texlive.outputs.cache-hit != 'true'
    - name: Run install-tl
      run: |
        install-tl-dir/install-tl --profile test/config/texlive_linux.profile
      if: steps.cache-texlive.outputs.cache-hit != 'true'
    - name: Run tlmgr install
      run: |
        tlmgr update --self
        tlmgr install collection-latex
        tlmgr install import subfiles latexmk makeindex
        tlmgr install chktex lacheck latexindent
      if: steps.cache-texlive.outputs.cache-hit != 'true'
    - name: Download latexindent binary
      run: |
        curl -s -O -L http://mirrors.ctan.org/support/latexindent/bin/linux/latexindent
        mv -f latexindent /tmp/texlive/bin/x86_64-linux/latexindent
        chmod +x /tmp/texlive/bin/x86_64-linux/latexindent
      if: steps.cache-texlive.outputs.cache-hit != 'true'
    - uses: actions/setup-node@v4
      with:
        node-version: '18'
    - run: |
        perl -v
        perl -MCwd -e 'print $Cwd::VERSION."\n";'
    - run: |
        latex -v
        latexmk -v
    - run: |
        npm ci
        npm run compile
    - name: Run tests
      run: xvfb-run -a npm run test | grep -v 'Failed to connect to the bus:\|is not in the list of known options\|gpu_memory_buffer_support_x11' ; test ${PIPESTATUS[0]} -eq 0
    - name: Archive test logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-log
        path: test/log/**/*.log