name: TeX Live on Windows
env:
  cache-version: v12
on: [push, pull_request]

permissions:
  contents: read

jobs:
  windows:
    runs-on: windows-latest
    timeout-minutes: 40
    steps:
    - name: Prepare git
      run: git config --global core.autocrlf false
    - uses: actions/checkout@v4
    - name: Set up PATH
      run: |
        echo "C:\strawberry\c\bin;C:\strawberry\perl\site\bin;C:\strawberry\perl\bin" >> $GITHUB_PATH
        echo "D:\texlive\bin\windows" >> $GITHUB_PATH
      shell: bash
    - name: Cache TeX Live
      id: cache-texlive
      uses: actions/cache@v4
      with:
        path: D:\texlive
        key: ${{ env.cache-version }}-${{ runner.os }}-texlive-essential
        restore-keys: |
          ${{ env.cache-version }}-${{ runner.os }}-texlive-essential
    - name: Download install-tl.zip
      run: |
        curl -s -O -L http://mirror.ctan.org/systems/texlive/tlnet/install-tl.zip
        unzip -q install-tl.zip
        mv install-tl-2* install-tl-dir
      if: steps.cache-texlive.outputs.cache-hit != 'true'
    - name: Run install-tl-windows.bat
      run: |
        install-tl-dir\install-tl-windows.bat --profile test\config\texlive_windows.profile
      if: steps.cache-texlive.outputs.cache-hit != 'true'
      shell: cmd
    - name: Run tlmgr install
      run: |
        tlmgr install collection-latex
        tlmgr install import subfiles latexmk makeindex
        tlmgr install chktex lacheck latexindent
      if: steps.cache-texlive.outputs.cache-hit != 'true'
    - name: Download latexindent binary
      run: |
        curl -s -O -L http://mirrors.ctan.org/support/latexindent/bin/windows/latexindent.exe
        mv -Force "latexindent.exe" "D:\texlive\bin\windows\latexindent-binary.exe"
      if: steps.cache-texlive.outputs.cache-hit != 'true'
    - uses: actions/setup-node@v4
      with:
        node-version: '18'
    - run: |
        perl -v
        perl -MCwd -e 'print $Cwd::VERSION."\n";'
    - run: |
        latex -v
        latexmk -v
    - run: |
        npm ci
        npm run compile
    - name: Run tests
      run: npm run test
    - name: Archive test logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-log
        path: test/log/**/*.log
